[package]
name = "ngx-mod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4"
foreign-types = "0.5"

ngx-derive = { version = "0.1", path = "../ngx-derive", default-features = false, features = [
    "module",
] }
ngx-rt = { version = "0.1", path = "../ngx-rt" }
ngx-sys = { version = "0.1", path = "../ngx-sys" }
