[package]
name = "ngx-upstream-module"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
merge = "0.1"

ngx-mod = { version = "0.1", path = "../../ngx-mod" }
